import Head from "next/head";
import styles from "../styles/Home.module.css";

const About = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Ejercicio 1</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="/">Home</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{" "}
					<code className={styles.code}>pages/index.js</code>
				</p>
			</main>
		</div>
	);
};

export default About;
